# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_num', models.CharField(max_length=20)),
                ('street_name', models.CharField(max_length=200)),
                ('street_name_post_type', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=140)),
                ('latitude', models.FloatField(blank=True, default=0, null=True)),
                ('longitude', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
    ]
